/**
 * @alaarab/ogrid-angular-radix
 *
 * Lightweight Angular data grid using Angular CDK for overlays.
 * This is the recommended "default" option for Angular developers.
 */

// Explicit named re-exports from base package (replaces export * for better tree-shaking).

// Core types
export type {
  ColumnFilterType,
  IDateFilterValue,
  IColumnFilterDef,
  IColumnMeta,
  IValueParserParams,
  ICellValueChangedEvent,
  ICellEditorProps,
  CellEditorParams,
  HeaderCell,
  HeaderRow,
  RowId,
  UserLike,
  UserLikeInput,
  FilterValue,
  IFilters,
  IFetchParams,
  IPageResult,
  IDataSource,
  IGridColumnState,
  RowSelectionMode,
  IRowSelectionChangeEvent,
  StatusBarPanel,
  IStatusBarProps,
  IActiveCell,
  ISelectionRange,
  SideBarPanelId,
  ISideBarDef,
  IVirtualScrollConfig,
  IColumnReorderConfig,
  IOGridApi,
  CsvColumn,
  StatusBarPart,
  StatusBarPartsInput,
  PaginationViewModel,
  GridContextMenuItem,
  IColumnHeaderMenuItem,
  GridContextMenuHandlerProps,
  ColumnHeaderMenuInput,
  ColumnHeaderMenuHandlers,
  ParseValueResult,
  AggregationResult,
  GridRowComparatorProps,
  ColumnPinState,
  IDropTarget,
  ICalculateDropTargetParams,
  IVisibleRange,
  HeaderFilterConfigInput,
  HeaderFilterConfig,
  CellRenderDescriptorInput,
  CellRenderDescriptor,
  CellRenderMode,
  OverlayRect,
  ISortState,
  ArrowNavigationContext,
  ArrowNavigationResult,
  ZIndexKey,
} from '@alaarab/ogrid-angular';

// Core value exports
export {
  toUserLike,
  isInSelectionRange,
  normalizeSelectionRange,
  escapeCsvValue,
  buildCsvHeader,
  buildCsvRows,
  exportToCsv,
  triggerCsvDownload,
  getCellValue,
  flattenColumns,
  buildHeaderRows,
  isFilterConfig,
  getFilterField,
  mergeFilter,
  deriveFilterOptionsFromData,
  getMultiSelectFilterFields,
  getStatusBarParts,
  getDataGridStatusBarConfig,
  getPaginationViewModel,
  PAGE_SIZE_OPTIONS,
  MAX_PAGE_BUTTONS,
  GRID_CONTEXT_MENU_ITEMS,
  COLUMN_HEADER_MENU_ITEMS,
  getContextMenuHandlers,
  getColumnHeaderMenuItems,
  formatShortcut,
  parseValue,
  numberParser,
  currencyParser,
  dateParser,
  emailParser,
  booleanParser,
  computeAggregations,
  processClientSideData,
  areGridRowPropsEqual,
  isRowInRange,
  getPinStateForColumn,
  reorderColumnArray,
  calculateDropTarget,
  computeVisibleRange,
  computeTotalHeight,
  getScrollTopForRow,
  getHeaderFilterConfig,
  getCellRenderDescriptor,
  resolveCellDisplayContent,
  resolveCellStyle,
  buildInlineEditorProps,
  buildPopoverEditorProps,
  debounce,
  measureRange,
  injectGlobalStyles,
  computeNextSortState,
  measureColumnContentWidth,
  AUTOSIZE_EXTRA_PX,
  AUTOSIZE_MAX_PX,
  findCtrlArrowTarget,
  computeTabNavigation,
  computeArrowNavigation,
  applyCellDeletion,
  rangesEqual,
  clampSelectionToBounds,
  computeAutoScrollSpeed,
  applyRangeRowSelection,
  computeRowSelectionState,
  formatCellValueForTsv,
  formatSelectionAsTsv,
  parseTsvClipboard,
  applyPastedValues,
  applyCutClear,
  applyFillValues,
  UndoRedoStack,
  validateColumns,
  validateRowIds,
  CHECKBOX_COLUMN_WIDTH,
  ROW_NUMBER_COLUMN_WIDTH,
  DEFAULT_MIN_COLUMN_WIDTH,
  CELL_PADDING,
  GRID_BORDER_RADIUS,
  DEFAULT_DEBOUNCE_MS,
  PEOPLE_SEARCH_DEBOUNCE_MS,
  SIDEBAR_TRANSITION_MS,
  Z_INDEX,
} from '@alaarab/ogrid-angular';

// Angular-specific types
export type {
  IColumnDef,
  IColumnGroupDef,
  IColumnDefinition,
  IOGridProps,
  IOGridClientProps,
  IOGridServerProps,
  IOGridDataGridProps,
  ColumnChooserPlacement,
  OGridPagination,
  OGridColumnChooser,
  OGridFilters,
  OGridSideBarState,
  DataGridLayoutState,
  DataGridRowSelectionState,
  DataGridEditingState,
  DataGridCellInteractionState,
  DataGridContextMenuState,
  DataGridViewModelState,
  DataGridPinningState,
  DataGridStateResult,
  SideBarProps,
  SideBarFilterColumn,
  IColumnHeaderFilterProps,
  IColumnChooserProps,
} from '@alaarab/ogrid-angular';

// Angular services and components
export {
  OGridService,
  DataGridStateService,
  DataGridLayoutHelper,
  DataGridEditingHelper,
  DataGridInteractionHelper,
  ColumnReorderService,
  VirtualScrollService,
  OGridLayoutComponent,
  StatusBarComponent,
  GridContextMenuComponent,
  SideBarComponent,
  MarchingAntsOverlayComponent,
  EmptyStateComponent,
  BaseOGridComponent,
  BaseDataGridTableComponent,
  BaseColumnHeaderFilterComponent,
  BaseColumnChooserComponent,
  BasePaginationControlsComponent,
  BaseInlineCellEditorComponent,
  INLINE_CELL_EDITOR_TEMPLATE,
  INLINE_CELL_EDITOR_STYLES,
  BasePopoverCellEditorComponent,
  POPOVER_CELL_EDITOR_TEMPLATE,
  POPOVER_CELL_EDITOR_OVERLAY_STYLES,
  OGRID_THEME_VARS_CSS,
  createDebouncedSignal,
  createDebouncedCallback,
  createLatestCallback,
} from '@alaarab/ogrid-angular';

// Export our UI components
export { OGridComponent } from './ogrid/ogrid.component';
export { DataGridTableComponent } from './datagrid-table/datagrid-table.component';
export { ColumnHeaderFilterComponent } from './column-header-filter/column-header-filter.component';
// IColumnHeaderFilterProps is now exported from @alaarab/ogrid-angular (base class)
export { ColumnChooserComponent } from './column-chooser/column-chooser.component';
// IColumnChooserProps is now exported from @alaarab/ogrid-angular (base class)
export { PaginationControlsComponent } from './pagination-controls/pagination-controls.component';
export { ColumnHeaderMenuComponent } from './column-header-menu/column-header-menu.component';
export { InlineCellEditorComponent } from './datagrid-table/inline-cell-editor.component';
export { PopoverCellEditorComponent } from './datagrid-table/popover-cell-editor.component';
