// Shared utilities re-exported from core
export {
  escapeCsvValue,
  buildCsvHeader,
  buildCsvRows,
  exportToCsv,
  triggerCsvDownload,
  getCellValue,
  flattenColumns,
  buildHeaderRows,
  getFilterField,
  mergeFilter,
  deriveFilterOptionsFromData,
  getMultiSelectFilterFields,
  getStatusBarParts,
  getDataGridStatusBarConfig,
  getPaginationViewModel,
  PAGE_SIZE_OPTIONS,
  MAX_PAGE_BUTTONS,
  GRID_CONTEXT_MENU_ITEMS,
  COLUMN_HEADER_MENU_ITEMS,
  getContextMenuHandlers,
  getColumnHeaderMenuItems,
  formatShortcut,
  parseValue,
  numberParser,
  currencyParser,
  dateParser,
  emailParser,
  booleanParser,
  computeAggregations,
  processClientSideData,
  computeNextSortState,
  measureColumnContentWidth,
  AUTOSIZE_EXTRA_PX,
  AUTOSIZE_MAX_PX,
  findCtrlArrowTarget,
  computeTabNavigation,
  rangesEqual,
  clampSelectionToBounds,
  computeAutoScrollSpeed,
  formatCellValueForTsv,
  formatSelectionAsTsv,
  parseTsvClipboard,
  applyPastedValues,
  applyCutClear,
  applyFillValues,
  computeArrowNavigation,
  applyCellDeletion,
  applyRangeRowSelection,
  computeRowSelectionState,
  UndoRedoStack,
} from '@alaarab/ogrid-core';
export type {
  CsvColumn,
  StatusBarPart,
  StatusBarPartsInput,
  GridContextMenuItem,
  GridContextMenuHandlerProps,
  PaginationViewModel,
  ParseValueResult,
  AggregationResult,
  IColumnHeaderMenuItem,
  ColumnHeaderMenuInput,
  ColumnHeaderMenuHandlers,
  ArrowNavigationContext,
  ArrowNavigationResult,
} from '@alaarab/ogrid-core';

// View model utilities (re-exported from core + React-specific getCellInteractionProps)
export {
  getHeaderFilterConfig,
  getCellRenderDescriptor,
  resolveCellDisplayContent,
  resolveCellStyle,
  buildInlineEditorProps,
  buildPopoverEditorProps,
  getCellInteractionProps,
} from './dataGridViewModel';
export type {
  HeaderFilterConfigInput,
  HeaderFilterConfig,
  CellRenderDescriptorInput,
  CellRenderDescriptor,
  CellRenderMode,
  CellInteractionHandlers,
} from './dataGridViewModel';
export { areGridRowPropsEqual, isRowInRange } from './gridRowComparator';
export type { GridRowComparatorProps } from './gridRowComparator';
