// Explicit named re-exports from base package (replaces export * for better tree-shaking).
// Types from core (via @alaarab/ogrid-vue  to  @alaarab/ogrid-core)
export type {
  ColumnFilterType,
  IDateFilterValue,
  IColumnFilterDef,
  IColumnMeta,
  IValueParserParams,
  ICellValueChangedEvent,
  CellEditorParams,
  IColumnGroupDef,
  HeaderCell,
  HeaderRow,
  IColumnDefinition,
  RowId,
  UserLike,
  UserLikeInput,
  FilterValue,
  IFilters,
  IFetchParams,
  IPageResult,
  IDataSource,
  IGridColumnState,
  RowSelectionMode,
  IRowSelectionChangeEvent,
  StatusBarPanel,
  IStatusBarProps,
  IActiveCell,
  ISelectionRange,
  SideBarPanelId,
  ISideBarDef,
  IVirtualScrollConfig,
  IColumnReorderConfig,
  IOGridApi,
  CsvColumn,
  StatusBarPart,
  StatusBarPartsInput,
  PaginationViewModel,
  GridContextMenuItem,
  IColumnHeaderMenuItem,
  GridContextMenuHandlerProps,
  ColumnHeaderMenuInput,
  ColumnHeaderMenuHandlers,
  ParseValueResult,
  AggregationResult,
  GridRowComparatorProps,
  ColumnPinState,
  IDropTarget,
  ICalculateDropTargetParams,
  IVisibleRange,
  OverlayRect,
  ISortState,
  ArrowNavigationContext,
  ArrowNavigationResult,
  ZIndexKey,
} from '@alaarab/ogrid-vue';

export {
  toUserLike,
  isInSelectionRange,
  normalizeSelectionRange,
  escapeCsvValue,
  buildCsvHeader,
  buildCsvRows,
  exportToCsv,
  triggerCsvDownload,
  getCellValue,
  flattenColumns,
  buildHeaderRows,
  isFilterConfig,
  getFilterField,
  mergeFilter,
  deriveFilterOptionsFromData,
  getMultiSelectFilterFields,
  getStatusBarParts,
  getDataGridStatusBarConfig,
  getPaginationViewModel,
  PAGE_SIZE_OPTIONS,
  MAX_PAGE_BUTTONS,
  GRID_CONTEXT_MENU_ITEMS,
  COLUMN_HEADER_MENU_ITEMS,
  getContextMenuHandlers,
  getColumnHeaderMenuItems,
  formatShortcut,
  parseValue,
  numberParser,
  currencyParser,
  dateParser,
  emailParser,
  booleanParser,
  computeAggregations,
  processClientSideData,
  areGridRowPropsEqual,
  isRowInRange,
  getPinStateForColumn,
  reorderColumnArray,
  calculateDropTarget,
  computeVisibleRange,
  computeTotalHeight,
  getScrollTopForRow,
  getHeaderFilterConfig,
  getCellRenderDescriptor,
  resolveCellDisplayContent,
  resolveCellStyle,
  buildInlineEditorProps,
  buildPopoverEditorProps,
  debounce,
  measureRange,
  injectGlobalStyles,
  computeNextSortState,
  measureColumnContentWidth,
  AUTOSIZE_EXTRA_PX,
  AUTOSIZE_MAX_PX,
  findCtrlArrowTarget,
  computeTabNavigation,
  computeArrowNavigation,
  applyCellDeletion,
  rangesEqual,
  clampSelectionToBounds,
  computeAutoScrollSpeed,
  applyRangeRowSelection,
  computeRowSelectionState,
  formatCellValueForTsv,
  formatSelectionAsTsv,
  parseTsvClipboard,
  applyPastedValues,
  applyCutClear,
  applyFillValues,
  UndoRedoStack,
  validateColumns,
  validateRowIds,
  CHECKBOX_COLUMN_WIDTH,
  ROW_NUMBER_COLUMN_WIDTH,
  DEFAULT_MIN_COLUMN_WIDTH,
  CELL_PADDING,
  GRID_BORDER_RADIUS,
  DEFAULT_DEBOUNCE_MS,
  PEOPLE_SEARCH_DEBOUNCE_MS,
  SIDEBAR_TRANSITION_MS,
  Z_INDEX,
} from '@alaarab/ogrid-vue';

// Vue-specific types
export type {
  IColumnDef,
  ICellEditorProps,
  IOGridProps,
  IOGridClientProps,
  IOGridServerProps,
  IOGridDataGridProps,
} from '@alaarab/ogrid-vue';

// Composable types
export type {
  UseOGridResult,
  UseOGridPagination,
  UseOGridColumnChooser,
  UseOGridLayout,
  UseOGridFilters,
  ColumnChooserPlacement,
  UseDataGridStateParams,
  UseDataGridStateResult,
  DataGridLayoutState,
  DataGridRowSelectionState,
  DataGridEditingState,
  DataGridCellInteractionState,
  DataGridContextMenuState,
  DataGridViewModelState,
  DataGridPinningState,
  UseActiveCellResult,
  EditingCell,
  UseCellEditingParams,
  UseCellEditingResult,
  UseCellSelectionParams,
  UseCellSelectionResult,
  UseClipboardParams,
  UseClipboardResult,
  UseRowSelectionParams,
  UseRowSelectionResult,
  UseKeyboardNavigationParams,
  UseKeyboardNavigationResult,
  UseFillHandleParams,
  UseFillHandleResult,
  UseUndoRedoParams,
  UseUndoRedoResult,
  ContextMenuPosition,
  UseContextMenuResult,
  UseColumnResizeParams,
  UseColumnResizeResult,
  UseColumnReorderParams,
  UseColumnReorderResult,
  UseVirtualScrollParams,
  UseVirtualScrollResult,
  UseFilterOptionsResult,
  UseTableLayoutParams,
  UseTableLayoutResult,
  UseColumnHeaderFilterStateParams,
  UseColumnHeaderFilterStateResult,
  UseTextFilterStateParams,
  UseTextFilterStateResult,
  UseMultiSelectFilterStateParams,
  UseMultiSelectFilterStateResult,
  UsePeopleFilterStateParams,
  UsePeopleFilterStateResult,
  UseDateFilterStateParams,
  UseDateFilterStateResult,
  UseColumnChooserStateParams,
  UseColumnChooserStateResult,
  InlineCellEditorType,
  UseInlineCellEditorStateParams,
  UseInlineCellEditorStateResult,
  UseRichSelectStateParams,
  UseRichSelectStateResult,
  UseSideBarStateParams,
  UseSideBarStateResult,
  DebouncedFn,
  UseColumnPinningParams,
  UseColumnPinningResult,
  UseColumnHeaderMenuStateParams,
  UseColumnHeaderMenuStateResult,
  UseDataGridTableSetupParams,
  UseDataGridTableSetupResult,
  MaybeShallowRef,
} from '@alaarab/ogrid-vue';

// Composables
export {
  useOGrid,
  useDataGridState,
  useActiveCell,
  useCellEditing,
  useCellSelection,
  useClipboard,
  useRowSelection,
  useKeyboardNavigation,
  useFillHandle,
  useUndoRedo,
  useContextMenu,
  useColumnResize,
  useColumnReorder,
  useVirtualScroll,
  useFilterOptions,
  useDebounce,
  useDebouncedCallback,
  useTableLayout,
  useColumnHeaderFilterState,
  useTextFilterState,
  useMultiSelectFilterState,
  usePeopleFilterState,
  useDateFilterState,
  useColumnChooserState,
  useInlineCellEditorState,
  useRichSelectState,
  useSideBarState,
  useColumnPinning,
  useColumnHeaderMenuState,
  useDataGridTableSetup,
} from '@alaarab/ogrid-vue';

// View model utilities
export type {
  HeaderFilterConfigInput,
  HeaderFilterConfig,
  CellRenderDescriptorInput,
  CellRenderDescriptor,
  CellRenderMode,
  CellInteractionHandlers,
  CellInteractionProps,
} from '@alaarab/ogrid-vue';

export { getCellInteractionProps } from '@alaarab/ogrid-vue';

// Factory and component types
export { createDataGridTable, type IDataGridTableUIBindings } from '@alaarab/ogrid-vue';
export { createInlineCellEditor, type CreateInlineCellEditorOptions } from '@alaarab/ogrid-vue';
export { createOGrid, type IOGridUIBindings } from '@alaarab/ogrid-vue';
export type { SideBarProps, SideBarFilterColumn } from '@alaarab/ogrid-vue';

// Main components
export { OGrid } from './OGrid/OGrid';
export { DataGridTable } from './DataGridTable/DataGridTable';
export { default as ColumnChooser } from './ColumnChooser/ColumnChooser.vue';
export type { IColumnChooserProps } from './ColumnChooser/types';
export { default as ColumnHeaderFilter } from './ColumnHeaderFilter/ColumnHeaderFilter.vue';
export type { IColumnHeaderFilterProps } from './ColumnHeaderFilter/types';
export { default as PaginationControls } from './PaginationControls/PaginationControls.vue';
export type { IPaginationControlsProps } from './PaginationControls/types';

// ColumnHeaderMenu
export { default as ColumnHeaderMenu } from './ColumnHeaderMenu/ColumnHeaderMenu.vue';
export type { ColumnHeaderMenuProps } from './ColumnHeaderMenu/types';

// Re-export shared components from base
export { StatusBar, MarchingAntsOverlay } from '@alaarab/ogrid-vue';
// DataGridTable sub-components
export { default as GridContextMenu } from './DataGridTable/GridContextMenu.vue';
export { InlineCellEditor } from './DataGridTable/InlineCellEditor';
