// Explicit named re-exports from core (replaces export * for better tree-shaking).

// Core types not already re-exported from ./types
export type {
  ISheetDef,
  IColumnReorderConfig,
  CsvColumn,
  FormulaExportOptions,
  StatusBarPart,
  StatusBarPartsInput,
  PaginationViewModel,
  GridContextMenuItem,
  IColumnHeaderMenuItem,
  GridContextMenuHandlerProps,
  ColumnHeaderMenuInput,
  ColumnHeaderMenuHandlers,
  ParseValueResult,
  AggregationResult,
  GridRowComparatorProps,
  ColumnPinState,
  IDropTarget,
  ICalculateDropTargetParams,
  IVisibleRange,
  IVisibleColumnRange,
  SortFilterRequest,
  SortFilterResponse,
  OverlayRect,
  ISortState,
  ArrowNavigationContext,
  ArrowNavigationResult,
  IFillFormulaOptions,
  FormulaReference,
  IResponsiveColumnsConfig,
  ZIndexKey,
  ICellAddress,
  ICellRange,
  CellKey,
  FormulaErrorType,
  TokenType,
  Token,
  ASTNode,
  BinaryOp,
  IFormulaContext,
  IFormulaFunction,
  IEvaluator,
  IRecalcResult,
  IFormulaEngineConfig,
  IGridDataAccessor,
  INamedRange,
  IAuditEntry,
  IAuditTrail,
  BooleanCellSelectHandlers,
} from '@alaarab/ogrid-core';

// Core utilities
export {
  escapeCsvValue,
  buildCsvHeader,
  buildCsvRows,
  exportToCsv,
  triggerCsvDownload,
  getCellValue,
  isColumnEditable,
  createGridDataAccessor,
  flattenColumns,
  buildHeaderRows,
  isFilterConfig,
  getFilterField,
  mergeFilter,
  deriveFilterOptionsFromData,
  getMultiSelectFilterFields,
  getStatusBarParts,
  getDataGridStatusBarConfig,
  getPaginationViewModel,
  PAGE_SIZE_OPTIONS,
  MAX_PAGE_BUTTONS,
  GRID_CONTEXT_MENU_ITEMS,
  COLUMN_HEADER_MENU_ITEMS,
  getContextMenuHandlers,
  getColumnHeaderMenuItems,
  formatShortcut,
  parseValue,
  numberParser,
  currencyParser,
  dateParser,
  emailParser,
  booleanParser,
  computeAggregations,
  processClientSideData,
  areGridRowPropsEqual,
  isRowInRange,
  getPinStateForColumn,
  reorderColumnArray,
  calculateDropTarget,
  computeVisibleRange,
  computeTotalHeight,
  getScrollTopForRow,
  computeVisibleColumnRange,
  partitionColumnsForVirtualization,
  createSortFilterWorker,
  terminateSortFilterWorker,
  extractValueMatrix,
  processClientSideDataAsync,
  CellDescriptorCache,
  debounce,
  measureRange,
  buildCellIndex,
  injectGlobalStyles,
  computeNextSortState,
  measureColumnContentWidth,
  AUTOSIZE_EXTRA_PX,
  AUTOSIZE_MAX_PX,
  findCtrlArrowTarget,
  computeTabNavigation,
  computeArrowNavigation,
  applyCellDeletion,
  rangesEqual,
  clampSelectionToBounds,
  computeAutoScrollSpeed,
  applyRangeRowSelection,
  computeRowSelectionState,
  formatCellValueForTsv,
  formatSelectionAsTsv,
  parseTsvClipboard,
  applyPastedValues,
  applyCutClear,
  applyFillValues,
  UndoRedoStack,
  validateColumns,
  validateRowIds,
  validateVirtualScrollConfig,
  indexToColumnLetter,
  columnLetterToIndex,
  formatCellReference,
  getResponsiveHiddenColumns,
  RESPONSIVE_BREAKPOINTS,
  resolveResponsiveConfig,
  applyResponsiveHiding,
  handleBooleanCellPointerDown,
} from '@alaarab/ogrid-core';

// Core constants
export {
  CHECKBOX_COLUMN_WIDTH,
  ROW_NUMBER_COLUMN_WIDTH,
  ROW_NUMBER_COLUMN_ID,
  ROW_NUMBER_COLUMN_MIN_WIDTH,
  DEFAULT_MIN_COLUMN_WIDTH,
  CELL_PADDING,
  GRID_BORDER_RADIUS,
  DEFAULT_DEBOUNCE_MS,
  PEOPLE_SEARCH_DEBOUNCE_MS,
  SIDEBAR_TRANSITION_MS,
  Z_INDEX,
} from '@alaarab/ogrid-core';

// Formula system (from @alaarab/ogrid-core/formula subpath)
export {
  FormulaError,
  FormulaEngine,
  FormulaEvaluator,
  DependencyGraph,
  tokenize,
  parse,
  createBuiltInFunctions,
  parseCellRef,
  parseRange,
  formatAddress,
  toCellKey,
  fromCellKey,
  adjustFormulaReferences,
  toNumber,
  formulaToString,
  toBoolean,
  flattenArgs,
  isFormulaError,
  REF_ERROR,
  DIV_ZERO_ERROR,
  VALUE_ERROR,
  NAME_ERROR,
  CIRC_ERROR,
  GENERAL_ERROR,
  NA_ERROR,
  extractFormulaReferences,
  processFormulaBarCommit,
  deriveFormulaBarText,
  handleFormulaBarKeyDown,
  canInsertReference,
  insertReferenceAtCursor,
  FORMULA_REF_COLORS,
  FORMULA_BAR_CSS,
  FORMULA_BAR_STYLES,
} from '@alaarab/ogrid-core/formula';

// Vue-specific types (override core's IColumnDef with Vue-specific version)
export type {
  IColumnDef,
  ICellEditorProps,
  IOGridProps,
  IOGridClientProps,
  IOGridServerProps,
  IOGridDataGridProps,
} from './types';

// Re-export all other types from the types barrel
export type {
  ColumnFilterType,
  IColumnFilterDef,
  IColumnMeta,
  IColumnGroupDef,
  IColumnDefinition,
  ICellValueChangedEvent,
  CellEditorParams,
  IValueParserParams,
  IDateFilterValue,
  HeaderCell,
  HeaderRow,
  RowId,
  UserLike,
  UserLikeInput,
  FilterValue,
  IFilters,
  IFetchParams,
  IPageResult,
  IDataSource,
  IGridColumnState,
  IOGridApi,
  RowSelectionMode,
  IRowSelectionChangeEvent,
  StatusBarPanel,
  IStatusBarProps,
  IActiveCell,
  ISelectionRange,
  SideBarPanelId,
  ISideBarDef,
  IVirtualScrollConfig,
} from './types';

export { toUserLike, isInSelectionRange, normalizeSelectionRange } from './types';

// Shared components
export { MarchingAntsOverlay } from './components/MarchingAntsOverlay';
export { StatusBar, type StatusBarProps } from './components/StatusBar';
export { FormulaBar, type FormulaBarProps } from './components/FormulaBar';
export { SheetTabs, type SheetTabsProps } from './components/SheetTabs';
export { FormulaRefOverlay } from './components/FormulaRefOverlay';

// Composables
export {
  useOGrid,
  useHeadlessGrid,
  useDataGridState,
  useActiveCell,
  useCellEditing,
  useCellSelection,
  useClipboard,
  useRowSelection,
  useKeyboardNavigation,
  useFillHandle,
  useUndoRedo,
  useInlineEdit,
  useRangeSelection,
  useCellClipboard,
  useGridFocus,
  useContextMenu,
  useColumnResize,
  useColumnReorder,
  useVirtualScroll,
  useFilterOptions,
  useDebounce,
  useDebouncedCallback,
  useTableLayout,
  useColumnHeaderFilterState,
  useTextFilterState,
  useMultiSelectFilterState,
  usePeopleFilterState,
  useDateFilterState,
  useColumnChooserState,
  useInlineCellEditorState,
  useRichSelectState,
  useSideBarState,
  useColumnPinning,
  useColumnHeaderMenuState,
  useDataGridTableSetup,
  useFormulaBar,
} from './composables';

// Composable types
export type {
  UseOGridResult,
  UseOGridPagination,
  UseOGridColumnChooser,
  UseOGridLayout,
  UseOGridFilters,
  ColumnChooserPlacement,
  UseHeadlessGridParams,
  UseHeadlessGridResult,
  HeadlessGridRowId,
  HeadlessGridSortState,
  UseDataGridStateParams,
  UseDataGridStateResult,
  DataGridLayoutState,
  DataGridRowSelectionState,
  DataGridEditingState,
  DataGridCellInteractionState,
  DataGridContextMenuState,
  DataGridViewModelState,
  DataGridPinningState,
  UseActiveCellResult,
  EditingCell,
  UseCellEditingParams,
  UseCellEditingResult,
  UseCellSelectionParams,
  UseCellSelectionResult,
  UseClipboardParams,
  UseClipboardResult,
  UseRowSelectionParams,
  UseRowSelectionResult,
  UseKeyboardNavigationParams,
  UseKeyboardNavigationResult,
  UseFillHandleParams,
  UseFillHandleResult,
  UseInlineEditParams,
  UseInlineEditResult,
  InlineEditEvent,
  InlineEditorProps,
  UseRangeSelectionParams,
  UseRangeSelectionResult,
  CellCoord,
  UseCellClipboardParams,
  UseCellClipboardResult,
  UseGridFocusParams,
  UseGridFocusResult,
  UseUndoRedoParams,
  UseUndoRedoResult,
  ContextMenuPosition,
  UseContextMenuResult,
  UseColumnResizeParams,
  UseColumnResizeResult,
  UseColumnReorderParams,
  UseColumnReorderResult,
  UseVirtualScrollParams,
  UseVirtualScrollResult,
  UseFilterOptionsResult,
  UseTableLayoutParams,
  UseTableLayoutResult,
  UseColumnHeaderFilterStateParams,
  UseColumnHeaderFilterStateResult,
  UseTextFilterStateParams,
  UseTextFilterStateResult,
  UseMultiSelectFilterStateParams,
  UseMultiSelectFilterStateResult,
  UsePeopleFilterStateParams,
  UsePeopleFilterStateResult,
  UseDateFilterStateParams,
  UseDateFilterStateResult,
  UseColumnChooserStateParams,
  UseColumnChooserStateResult,
  InlineCellEditorType,
  UseInlineCellEditorStateParams,
  UseInlineCellEditorStateResult,
  UseRichSelectStateParams,
  UseRichSelectStateResult,
  UseSideBarStateParams,
  UseSideBarStateResult,
  DebouncedFn,
  UseColumnPinningParams,
  UseColumnPinningResult,
  UseColumnHeaderMenuStateParams,
  UseColumnHeaderMenuStateResult,
  UseDataGridTableSetupParams,
  UseDataGridTableSetupResult,
  MaybeShallowRef,
  UseFormulaBarParams,
  UseFormulaBarResult,
} from './composables';

// View model utilities (for UI packages)
export {
  getHeaderFilterConfig,
  getCellRenderDescriptor,
  resolveCellDisplayContent,
  resolveCellStyle,
  buildInlineEditorProps,
  buildPopoverEditorProps,
  getCellInteractionProps,
} from './utils';

export type {
  HeaderFilterConfigInput,
  HeaderFilterConfig,
  CellRenderDescriptorInput,
  CellRenderDescriptor,
  CellRenderMode,
  CellInteractionHandlers,
  CellInteractionProps,
} from './utils';

// DataGridTable factory (for UI packages)
export { createDataGridTable, type IDataGridTableUIBindings } from './components/createDataGridTable';

// InlineCellEditor factory (for UI packages)
export { createInlineCellEditor, type CreateInlineCellEditorOptions } from './components/createInlineCellEditor';

// OGrid factory (for UI packages)
export { createOGrid, type IOGridUIBindings } from './components/createOGrid';

// Component types (for UI packages to implement)
export type { SideBarProps, SideBarFilterColumn } from './components/SideBar';
